name: Generate Snake

on:
  schedule: # Runs at every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch: # Allows to run workflow manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: ARJ010  # Replace with your GitHub username
          outputs: dist/snake.svg

      # Upload the snake image
      - name: Push generated snake
        uses: actions/upload-artifact@v2
        with:
          name: snake-contribution-grid
          path: dist/snake.svg
